### ISSUE TITLE
Encoding types

### ISSUE THREAD

**Issue by ivangutierrezr** [giorgiofellipe/cordova-plugin-datecs-printer#10]
Hi brother! it's me again haha, sorry.

I'm trying to print some characters in spanish as " ñ " and vowels like " á é í ó ú" with accent. Which econding type accepts your plugin for this? ISO-8859-1 doesn't print that characters...
Thanks and sorry one more time.

**Comment by gustavocampos** [comment]
I tried UTF-8 and it doesn't work also

**Comment by giorgiofellipe** [comment]
Hm, curious... I'm using ISO-8859-1 and it is working fine. 

Could any of you share a starter project where it is happening? @ivangutierrezr @gustavocampos

**Comment by konlawatch** [comment]
help me please.
problem print slip on thai language not work.

**Comment by giorgiofellipe** [comment]
@konlawatch please open a new issue with more detailed description on your error and example code, thanks.
