### ISSUE TITLE
Cant make it work for android 7.0.0

### ISSUE THREAD

**Issue by lumon86** [giorgiofellipe/cordova-plugin-datecs-printer#111]
Hi i want to know of somebody make it work for android 7.0.0 Im build an application with salesforce and this greate plugin, but a few days ago i tried to make an update to android 7.0.0 but when i install this plugin i cant make it work. it says that cant find the android manifiest and this is because the android 7.0.0 has a new file structure. Can you help me ?

**Comment by danielCespedes** [comment]
lumon86,

I am using Cordova to create my App. In order to solved your problem I used the following lines in my config.xml

<plugin name="cordova-android-support-gradle-release" spec="^1.4.2">
        <variable name="ANDROID_SUPPORT_VERSION" value="27.+" />
    </plugin>

**Comment by giorgiofellipe** [comment]
Should be working on version 0.8.3.
