### ISSUE TITLE
Error when I tried to print image

### ISSUE THREAD

**Issue by jomora15** [giorgiofellipe/cordova-plugin-datecs-printer#126]
Hi! 
I'm trying to print in a Datamax o'neil Apex2 printer. Print text works perfectly but image or barcode doesn't work. This is the image error.

![error](https://user-images.githubusercontent.com/29065734/50247939-50b56e00-03a7-11e9-95ab-85e2a64a0831.jpeg)

**My code:**
`testPrint(printerAddress) {
window.DatecsPrinter.connect(printerAddress, () => {
      window.DatecsPrinter.printImage(printData, 200, 200, 1, () => {
        alert('imprio');
      }, (err) => { alert('no imprio ' +JSON.stringify(err)); })
    },
      (err) => alert('err: ' + JSON.stringify(err)));
  }`

printData is a base64 string.

When I'm trying to print BarCode I have timeout

![bc](https://user-images.githubusercontent.com/29065734/50251236-35e7f700-03b1-11e9-8087-57d0bea756b9.jpeg)

**My code for barcode**

`window.DatecsPrinter.connect(printerAddress, () => {
      window.DatecsPrinter.printBarcode(
        75, //here goes the barcode type code
        '13132498746313210584982011487', //your barcode data
        () => {
          alert('success!');
        },
        (error) => {
          alert(JSON.stringify(error));
        }
      );
    },
      (err) => alert('err: ' + JSON.stringify(err)));`

Thanks!

**Comment by csleeds** [comment]
For image printing, i do face the same issue like this before, there is a workaround for that but i'm not sure if it will works all the time as i believe the core issue is due to unsupported/ partially supported printer model. 

Try trigger a text print before you print an image:
window.DatecsPrinter.printText("{br}", 'UTF-8',
	function () {
		window.DatecsPrinter.printImage(
			printData,
			200,
			200,
			1,
			function () {
			},
			function (error) {
				alert(JSON.stringify(error));
			}
		);
	},
	function (error) {
		alert(JSON.stringify(error));
	}
);

Let me know if this works for you too.
