### ISSUE TITLE
Print QR Codes

### ISSUE THREAD

**Issue by gustavocampos** [giorgiofellipe/cordova-plugin-datecs-printer#13]
Giorgio eu vi que o driver possui impressão de QR Codes mas você não implementou o método, tentei implementar mas não funcionou na impressora que tenho, você chegou a tentar usar?

Estou imprimindo como imagem mas fica bem lenta a impressão, mesmo num tamanho pequeno 1,5cm x 1,5cm.

**Comment by giorgiofellipe** [comment]
Na verdade não cheguei a tentar não cara...

Faz um fork desse repositório, implementa o que você testou que eu ajudo a finalizar/ver o que falta pra funcionar corretamente!

A impressora que vc tá usando é a DPP-250?

**Comment by gustavocampos** [comment]
Vou fazer.

Na verdade estou usando uma impressora genérica que é compatível com ESC/POS, em teoria todas deveriam imprimir a mesma coisa.

**Comment by gustavocampos** [comment]
Implementei num fork e atualizei a lib da impressora, se quiser testar

https://github.com/gustavocampos/cordova-plugin-datecs-printer

plugin: cordova-plugin-datecs-printer-qr

na minha impressora genérica sai como texto comum

**Comment by jdiiego** [comment]
Hola, amigo he tratado de imprimir el código de barras con el plugin cordova-plugin-datecs-printer, pero no me imprime nada, solo unos caracteres especiales, me podrían ayudar?
Gracias!!

**Comment by rspedrini** [comment]
Gustavo e Giorgio,

Estou implementando uma solução com a DPP-450 e esbarrei nesse plugin que vocês mexeram, vi que implementaram os métodos de page mode, mas não achei o "setPageXY" implementado, realmente não tem nesse plugin né?

Até então eu estava enviando todos os dados byte a byte em outras impressoas escpos, mas como hoje peguei outra impressora pra homologar estou buscando algo mais amigável até para manutenabilidade futuramente se outra pessoa for mexer no aplicativo.

Valeu!

**Comment by gustavocampos** [comment]
Essa parte eu não mexi, acredito que já tinha no plugin do Giorgio, eu não utilizei.

**Comment by rspedrini** [comment]
O "setPageXY" acho que realmente não está, qualquer coisa implemento os que eu vou precisar e contribuo depois. Você chegou a utilizar o page mode sem precisar definir o XY? Não conseguir ver outra forma de utilizar o potencial do page mode sem definir o XY...

**Comment by giorgiofellipe** [comment]
@rspedrini realmente não implementei esse método, na verdade toda a implementação de impressão em page mode não foi devidamente testada...
Fique a vontade pra mandar um PR com as implementações.

**Comment by rakeshravipati** [comment]
Gustavo and Giorgio,

I have tried using plugin: cordova-plugin-datecs-printer-qr with ionic app.
When I tried to build app for android I have Java compile error, i.e.

:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:35:
        error: package android.support.v4.content does not exist
        import android.support.v4.content.LocalBroadcastManager;
        ^
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:620:
        error: cannot find symbol
        LocalBroadcastManager.getInstance(mWebView.getContext()).sendBroadcastSync(intent);
        ^
        symbol:   variable LocalBroadcastManager
        location: class DatecsSDKWrapper
        Note: /Users/swdev/Desktop/printqrapp/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java
        uses or overrides a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note:
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java
        uses unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.
        2 errors
        :compileDebugJavaWithJavac FAILED

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

        BUILD FAILED

        Total time: 3.275 secs
        Error: /Users/swdev/Desktop/printqrapp/platforms/android/gradlew: Command failed with exit code 1 Error output:
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:35:
        error: package android.support.v4.content does not exist
        import android.support.v4.content.LocalBroadcastManager;
        ^
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:620:
        error: cannot find symbol
        LocalBroadcastManager.getInstance(mWebView.getContext()).sendBroadcastSync(intent);
        ^
        symbol:   variable LocalBroadcastManager
        location: class DatecsSDKWrapper
        Note: /Users/swdev/Desktop/printqrapp/platforms/android/src/org/apache/cordova/splashscreen/SplashScreen.java
        uses or overrides a deprecated API.
        Note: Recompile with -Xlint:deprecation for details.
        Note:
        /Users/swdev/Desktop/printqrapp/platforms/android/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java
        uses unchecked or unsafe operations.
        Note: Recompile with -Xlint:unchecked for details.
        2 errors

        FAILURE: Build failed with an exception.

        * What went wrong:
        Execution failed for task ':compileDebugJavaWithJavac'.
        > Compilation failed; see the compiler error output for details.

        * Try:
        Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by giorgiofellipe** [comment]
@rakeshravipati it's not about the plugin itself. Please update your SDK and do further research on stackoverflow.

**Comment by rakeshravipati** [comment]
Sorry about it. I will search the issue. Thanks.
