### ISSUE TITLE
Reduce font size or change font family

### ISSUE THREAD

**Issue by testaccnt0435** [giorgiofellipe/cordova-plugin-datecs-printer#14]
I  have tried your plugin, printer allow 28 character / each line. But i need to reduce the font size and print   the more character in single line. I have tried {h},{s},{w} tag but there is no change. Kindly guide me how to reduce it . {center}tag also not working , {br} only allowed. My bluetooth printer model is "ANALOGICS"  and model number is "AET36015". My code is 
window.DatecsPrinter.printText("{b}{center}VIJAY HOME FOODS (P) LTD{/b}{br}");

**Comment by giorgiofellipe** [comment]
This plugin is tightly coupled with Datecs library and can not work with other printers.
