### ISSUE TITLE
Reduce font size & print more character in each line

### ISSUE THREAD

**Issue by testaccnt0435** [giorgiofellipe/cordova-plugin-datecs-printer#15]
I need to print more character(now 28 characters / each line) and also formatting some style(reduce font size) while printing. Tag defination {s}, {/s} not supported in INTEL XDK.

**Comment by megatdaharus** [comment]
Hi...

I also need a help to print multiple font size

**Comment by giorgiofellipe** [comment]
So, these are the font styler available:

- {b}, {/b} Set or clear bold font style.
- {u}, {/u} Set or clear underline font style.
- {i}, {/i} Set or clear italic font style.
- {s}, {/s} Set or clear small font style.
- {h}, {/h} Set or clear high font style.
- {w}, {/w} Set or clear wide font style.

Why it's not supported by INTEL XDK? Couldn't understand...

**Comment by megatdaharus** [comment]
Hi…

Thank for feedback…

I successful using your code in ionic using Oneil and StartPrinter.
My other problem is, i cannot print barcode and image using both printer,

I’m have a jar SDK for printer, how to integrate that

Thank you

**Comment by jakeb-cloud** [comment]
Hi @megatdaharus,

Did you experience when printing text. There is a Capitalize i on the first line?


Thanks

**Comment by megatdaharus** [comment]
HI…

Here the final result

I need to print 2 barcode for the header and 1 e-signature (jpg)...

**Comment by jakeb-cloud** [comment]
Hi @megatdaharus,

Is the 2 barcode and 1 image is successfully printed?

Thanks

**Comment by megatdaharus** [comment]
Hi…

Not success…

**Comment by megatdaharus** [comment]
Hi…

Can u help me to build a plugin using datamax-oneil (microflach 4Te) & star print sdk

I will pay for it…

thank you

**Comment by giorgiofellipe** [comment]
@megatdaharus ping me giorgiofellipe@gmail.com

**Comment by megatdaharus** [comment]
Hi…

Can u help me to build a plugin using datamax-oneil (microflach 4Te) & star print sdk

I will pay for it…

thank you

**Comment by giorgiofellipe** [comment]
@megatdaharus I surely can, what is your email?

**Comment by mariano-aguero** [comment]
The first tag is not aligned to the left
