### ISSUE TITLE
Error building with Phonegap-build

### ISSUE THREAD

**Issue by SrMordred** [giorgiofellipe/cordova-plugin-datecs-printer#17]
The build fails after the recent update:

on config.xml:
`<gap:plugin source="npm" name="cordova-plugin-datecs-printer" />`

Phonegap Build (Android) shows:
_"Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: DatecsPrinter.java"_

**Comment by giorgiofellipe** [comment]
@SrMordred version 0.4.5 is out and stable, give it a try
