### ISSUE TITLE
printText function is always having 'I' character in the firstline.

### ISSUE THREAD

**Issue by jakeb-cloud** [giorgiofellipe/cordova-plugin-datecs-printer#19]

**Comment by jakeb-cloud** [comment]
window.DatecsPrinter.printText("Print Test!", 'ISO-8859-1') and the output is =  IPrint Test!

**Comment by jakeb-cloud** [comment]
![2016-11-03 09 36 15](https://cloud.githubusercontent.com/assets/20410058/19964631/c8a020da-a1fd-11e6-8c43-ad1904a7549f.jpg)

How can get rid the capital I?

Thanks

**Comment by giorgiofellipe** [comment]
@jakeb-cloud 
Can't figure out why it is printing this capitalized i for you.
Are you using the latest release?
Could you share a sample project?

**Comment by jakeb-cloud** [comment]
Hi @giorgiofellipe ,

Here's my code.

$scope.print = function(){
    window.DatecsPrinter.listBluetoothDevices(
      function (devices) {
        alert(JSON.stringify(devices));
        window.DatecsPrinter.connect(devices[1].address, 
          function() {
            printSomeTestText();
          },
          function() {
            alert(JSON.stringify(error));
          }
        );
      },
      function (error) {
        alert(JSON.stringify(error));
      }
    );

    function printSomeTestText() {
      window.DatecsPrinter.printText("{center}Print Test!\n\n\n", 'ISO-8859-1', 
        function() {
          alert("TEXT printed");
        }
      );
    }
  }

**Output**
![print](https://cloud.githubusercontent.com/assets/20410058/20043060/347cbbfe-a4c1-11e6-82af-81eed979e432.jpg)


By the way. I'm using the latest release.  version="0.4.5"

Thanks

**Comment by wailynnoo** [comment]
@giorgiofellipe  I also got this error start with I character. How should i fix?
