### ISSUE TITLE
how do I print out the string with a align right and left in one line

### ISSUE THREAD

**Issue by ridlosmartit** [giorgiofellipe/cordova-plugin-datecs-printer#20]
Here is the example:
![old-big](https://cloud.githubusercontent.com/assets/23231105/19958017/1cd09f98-a1ce-11e6-8bed-6cffc1e4e6b9.png)

Sorry for my bad english

Many Thanks :)

**Comment by jakeb-cloud** [comment]
Hi @ridlosmartit,

You can use this.

{left} Aligns text to the left paper edge.
{center} Aligns text to the center of paper.
{right} Aligns text to the right paper edge.

**Comment by ridlosmartit** [comment]
Hi @jakeb-cloud , @giorgiofellipe
Here is my code:
var printStr = "";
for (var i = 0; i < 3; i++) {
      printStr += "LEFT{left}";
      printStr += " CENTER{center}";
      printStr += " RIGHT{right}";
      printStr += "{br}";
}

function printSomeTestText() {
  window.DatecsPrinter.printText(printStr, 'ISO-8859-1', 
    function() {
       //code
    }
  );
}

And then the result like below
![20161104_140552](https://cloud.githubusercontent.com/assets/23231105/19997384/c8c8c03a-a298-11e6-908b-9c279e56cbbc.jpg)
What's wrong..??

Thanks

**Comment by jakeb-cloud** [comment]
@ridlosmartit,

Here's the sample:

{center}Center {br}
{left}Left  {right}Right

**Comment by giorgiofellipe** [comment]
@ridlosmartit 
I've noticed that not all printers support lines with multi-alignments...
In case of doing something like that you showed early "Product .... price", you can achieve that by doing something like this:

```js
function pad(string1, string2, size) {
  var finalString = string1;
  var paddingSize = size - string1.length - string2.length;
  finalString += ' '.repeat(paddingSize) + string2;
  return finalString;
}
```

Eg.:
```js
pad('Coca-cola', '$ 2.00', 40); //"Coca-cola                         $ 2.00"
```

**Comment by ridlosmartit** [comment]
Hi @jakeb-cloud, @giorgiofellipe 

Thanks for your help
It Works

Many Thanks 😄
