### ISSUE TITLE
Error for ionic build android

### ISSUE THREAD

**Issue by alanschlindvein** [giorgiofellipe/cordova-plugin-datecs-printer#21]
Hi, I'm getting this problem when I'm trying build my app. I have all extras installed in sdk manager.

Error: cmd: Command failed with exit code 1 Error output:
C:\Users\alan.araujo.NT\Desktop\fxd-mobile\platforms\android\src\com\giorgiofellipe\datecsprinter\DatecsSDKWrapper.java:36: error: package android.support.v4.content does not exist
import android.support.v4.content.LocalBroadcastManager;
                                 ^
C:\Users\alan.araujo.NT\Desktop\fxd-mobile\platforms\android\src\com\giorgiofellipe\datecsprinter\DatecsSDKWrapper.java:646: error: cannot find symbol
        LocalBroadcastManager.getInstance(mWebView.getContext()).sendBroadcastSync(intent);
        ^
  symbol:   variable LocalBroadcastManager
  location: class DatecsSDKWrapper
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by giorgiofellipe** [comment]
@alanschlindvein Fixed. Try the new version (0.4.7)

**Comment by alanschlindvein** [comment]
It worked =D. Thanks @giorgiofellipe . I had the 0.4.5 version using cordova-plugin-android-support-v4 to get this working.

**Comment by giorgiofellipe** [comment]
@alanschlindvein it's a workaround, but seems prettier to not depend on it
