### ISSUE TITLE
Erro ao Usar intelXDK

### ISSUE THREAD

**Issue by carlosfred** [giorgiofellipe/cordova-plugin-datecs-printer#27]
Giorgio, o plugin parou de funcionar no intelXDK, até 2 dias atrás estava funcionado perfeitamente, estou testando o plugin e hoje não estou mais conseguindo fazer o build, voce fez algumas alterações nos ultimos dias ?

**Comment by giorgiofellipe** [comment]
@carlosfred sim, o plugin foi atualizado da versão 0.4.7 pra versão 0.5.1...
poderia detalhar melhor qual o problema?

**Comment by carlosfred** [comment]
Não sei se voce utiliza o intelXDK, mas quando mando dar um build ele diz que não pode instalar o plugin.

**Comment by giorgiofellipe** [comment]
@carlosfred existe algum log?

**Comment by carlosfred** [comment]
Rapaz, acho que não tem log não, sou meio cru em intelxdk.

**Comment by giorgiofellipe** [comment]
Também não conheço o Intel XDK, mas acredito que deva existir um log de compilação.
Se puder encontra-lo e colocá-lo aqui poderei ajudar melhor! ;)

**Comment by giorgiofellipe** [comment]
Fechado por falta de informações, se for necessário é só pedir a reabertura.
