### ISSUE TITLE
Align left and align right on same line

### ISSUE THREAD

**Issue by matheusgs05** [giorgiofellipe/cordova-plugin-datecs-printer#28]
I'm trying to display a text aligned to the left and aligned to right on the same line.
The "|" character is the paper limit.
Something like this:
| XXXX                                      YYYY |

Everytime I try to print, the text is aligned everything to right or left, like:
| XXXXYYYY                                       |

Is it possible to print on same line with 2 alignments? Can you send an example?

**Comment by giorgiofellipe** [comment]
@matheusgs05 please search before asking...

Already answered this question on #20: https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/20#issuecomment-258476341
