### ISSUE TITLE
Error while printing text

### ISSUE THREAD

**Issue by ykarthikreddy18** [giorgiofellipe/cordova-plugin-datecs-printer#29]
Hi,

I'm getting the following error when I invoke print function for text

{"errorCode":5,"message":"Error printing","exception":"Broken pipe"}

This my print code

`function printSomeTestText() {`
` window.DatecsPrinter.printText("Print Test!", 'ISO-8859-1', `
`          function() {`
`            alert('print success')`
  `        },`
`            function(error) {`
`              console.log(JSON.stringify(error));`
`            }`
`          );`
`        }`

**Comment by giorgiofellipe** [comment]
@ykarthikreddy18 what is your printer model?

**Comment by ykarthikreddy18** [comment]
@giorgiofellipe .. thankyou for your response, that error occurred because I didnt closed the connection to that printer..
