### ISSUE TITLE
what are your printers?

### ISSUE THREAD

**Issue by terrapin3** [giorgiofellipe/cordova-plugin-datecs-printer#30]
This plugin works fine. Thank george. I'm using: 58mm thermal printer. I'm interested to know the other compatible models. what are your printers?

**Comment by giorgiofellipe** [comment]
Theorically it should work on every esc/pos thermal printers. But some vendors does shit and it doesn't work as expected. As said on [README](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/blob/master/README.md) this plugin is tested by me only on Datecs printers. Some people also reported other printer models that it is working fine, you can see the models [here](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/blob/master/README.md#reported-working-printer-models).
