### ISSUE TITLE
Bixolon SPP-R210

### ISSUE THREAD

**Issue by z3dman** [giorgiofellipe/cordova-plugin-datecs-printer#31]
Thank you Giorgio Fellipe!! Your plugin worked like a charm for Bixolon SPP-R210 thermal printer and your ionic service saved me a hell lot of time. I owe you a beer mate! :)

**Comment by giorgiofellipe** [comment]
Thank you dude! I'm glad to help 💃 

I'll add this model to the list, thanks!
