### ISSUE TITLE
$window.DatecsPrinter is undefined

### ISSUE THREAD

**Issue by phonsay** [giorgiofellipe/cordova-plugin-datecs-printer#32]
-I have download cordova-plugin-datecsprinter-example-master and run it, but I got the error $window.DatecsPrinter is undefined.
I already installed plugin cordova-plugin-datecs-printer.
-How to solved it?.
-when I add the code on this website to my ionic project, it has the same problem 'window.DatecsPrinter is undefined'.
Help me please.

**Comment by giorgiofellipe** [comment]
> As well as any other plugin it will only be available after deviceready event is fired

_Read the docs._

**Comment by phonsay** [comment]
You mean that it will work after mobile connect with printer  right?

**Comment by giorgiofellipe** [comment]
@phonsay cordova fire this event `deviceready` when it's loaded
