### ISSUE TITLE
Comandos POS / ESC

### ISSUE THREAD

**Issue by otavioboari** [giorgiofellipe/cordova-plugin-datecs-printer#33]
Teria como colocar comandos POS / ESC para ir direto para a impressora?

Ex: 1B 61 01 para centralizar, 1D 68 50 para altura do código de barras, etc...

Digo isso pois gostaria de personalizar os textos logo após a logo e não consigo aqui.

**Comment by giorgiofellipe** [comment]
É possível, porém não foi implementado...
Se você consultar a documentação da biblioteca utilizada existe o método `write(byte[] b, int offset, int length)`.

```
public void write(byte[] b,
                  int offset,
                  int length)
           throws java.io.IOException
Writes length bytes from the specified byte array to this printer.
If b is null, a NullPointerException is thrown.

if offset is negative, or length is negative, or offset + length is greater than the length of the array b, then an IndexOutOfBoundsException is thrown.

Parameters:
b - the data.
offset - the start offset in the data.
length - the number of bytes to write.
Throws:
java.io.IOException - if an I/O error occurs.
```

**Comment by giorgiofellipe** [comment]
@otavioboari foi implementado (há algum tempinho já, esqueci de avisar antes)!
`write` e `writeHex`
