### ISSUE TITLE
print recipe designing on ionic view(html) by this plugin

### ISSUE THREAD

**Issue by takoy123** [giorgiofellipe/cordova-plugin-datecs-printer#35]
Help me please, I have designed a recipe in html but how to print it by this plugin?

**Comment by giorgiofellipe** [comment]
It isn't possible to print html formatted text.
Check out how to format your text [here](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#tags-definition).

**Comment by takoy123** [comment]
Do you have another solution for me?

**Comment by giorgiofellipe** [comment]
Unfortunately no. :(

**Comment by takoy123** [comment]
Now, I can print html contents by this plugin. Thank you.

Sent from my ASUS

-------- Original Message --------

**Comment by mithunvp** [comment]
Can you share sample code for printing HTML contents using tag definitions. ? It would be much help

**Comment by vinay368** [comment]
hi takoy123 you told before "Now, I can print html contents by this plugin. Thank you." can you please share sample i need help. Thanks
