### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by wachgt** [giorgiofellipe/cordova-plugin-datecs-printer#36]
Hi, I've created a phonegap app and I'm trying to run it with the phonegap desktop but when I run it in my device it does nothing. Do I have to create the apk and install it for the plugin to work?

Thanks!

**Comment by giorgiofellipe** [comment]
No, you can test it just running. Could you provide more info about your problem? What are you doing, what you already done and if you got some error message?

**Comment by wachgt** [comment]
Hi, thank you... I've created a Hello World project in phonegap and added the reference to the plugin, I've check and there are already the plugin folder and the native an js files, but when I call the scan function nothing happens. I added a console log in the success function and in the error function as well, and those don't appear in the log. I am attaching my project html and js files so you can tell me what I'm doing wrong. I will create my apk to try if this solves my problem too. Thanks!
[Phonegap.zip](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/files/843101/Phonegap.zip)

**Comment by giorgiofellipe** [comment]
After `deviceready` event is fired check if the plugin is loaded properly, you can do a `console.log(window.DatecsPrinter)` to check it out

**Comment by giorgiofellipe** [comment]
A week is gone, I'll consider this as solved.
