### ISSUE TITLE
The result is not the same origine imaes after printing

### ISSUE THREAD

**Issue by takoy123** [giorgiofellipe/cordova-plugin-datecs-printer#37]
There are the problem when i print For example, Ả ả Ã ã Ạ ạ Ắ ắ Ằ ằ  Ẻ ẻ Ẽ ẽ Ẹ ẹ Ế ế Ề ề Ể ể Ễ ễ Ệ ệ, etc. 
but the result when i print is A a A a A a A a E e E e E. 
So I want the result like Ả ả Ã ã Ạ ạ Ắ ắ Ằ ằ  Ẻ ẻ Ẽ ẽ Ẹ ẹ Ế ế Ề ề Ể ể Ễ . How t solve it. I use print image method.
when use myImage.arc='img/test.png' it is working but I don't want to save image before print. i want to convert to basse64 and print it, 
My code bellow:

function printMyImage() {
          var imagedata;
          html2canvas([document.getElementById('mainDiv')], {
            background:'#fff',
            onrendered: function (canvas) {
              imagedata = canvas.toDataURL('image/png');
             // imagedata = canvas.toDataURL();

              var myImage = new Image();

              myImage.src = imagedata;
              myImage.onload = function () {
                var canvas = document.createElement("canvas");
                canvas.height = 300;
                canvas.width = 200;
                var context = canvas.getContext('2d');
                context.drawImage(myImage, 0, 0);

              //  var imageBase = canvas.toDataURL('image/png').replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
                var imageBase = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
                //var imageBase=canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
                window.DatecsPrinter.printImage(
                  imageBase, //base64
                  canvas.width,
                  canvas.height,
                  1,
                  function () {
                    //printMyBarcode();
                  },
                  function (error) {
                    alert(JSON.stringify(error));
                  }
                )
              }
            }
          })
        }

**Comment by giorgiofellipe** [comment]
`printText` method accepts two parameters, the first one is the text and the second is the charset, by default it's using ISO-8859-1.

About the image you can search and ask it on [StackOverflow](http://stackoverflow.com/), it's more a general doubt than something about the plugin.
