### ISSUE TITLE
print image URL lost data

### ISSUE THREAD

**Issue by takoy123** [giorgiofellipe/cordova-plugin-datecs-printer#39]
I have image url 
var  imageBase2 = canvas.toDataURL('image/png');
            var image1 = new Image();
            image1.src =imageBase2;
How to print image URL by this plugin?, I already print but the result missing some data

**Comment by giorgiofellipe** [comment]
As you can read on [README](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#cordova-plugin-datecs-printer) the `printImage` method expects the image base64. You can also find an example [here](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#example).
