### ISSUE TITLE
Is there a way to handle unspected errors?

### ISSUE THREAD

**Issue by AcTiv3MineD** [giorgiofellipe/cordova-plugin-datecs-printer#40]
Hello, is there a way for the developer to handle unexpected errors such as:
-When the printer turns off during the printing process.
-When printer runs out of paper

**Comment by giorgiofellipe** [comment]
Some printer brands change the printer status, others doesn't. (`getStatus`)
Some close the connection, others doesn't. (listen to the event `'DatecsPrinter.connectionStatus'`)

**Comment by giorgiofellipe** [comment]
Closing due to long time without activity.
If necessary I'll reopen.
