### ISSUE TITLE
Problems with accents

### ISSUE THREAD

**Issue by Filmulti** [giorgiofellipe/cordova-plugin-datecs-printer#41]
Good work Giorgio,

I am Spanish and we have the problem of accents when sending a text to the printer, I already tried UTF-8 and ISO-8859-1, but it prints badly. Is there any way to send encoded and to print the accents correctly?

Thanks!

**Comment by giorgiofellipe** [comment]
@Filmulti what is your printer model? Have you read about some limitation on the manual? Maybe a printer config?

**Comment by giorgiofellipe** [comment]
Closing due to long time without activity.
If necessary I'll reopen.
