### ISSUE TITLE
Plugin not working on Ionic 2

### ISSUE THREAD

**Issue by citerio** [giorgiofellipe/cordova-plugin-datecs-printer#42]
Hey Giorgio, I installed your awesome plugin on an Ionic 2 project, I am pretty sure it is well installed, but I don't know why it is not working, it is happening either the methods are not being called or are being called but doing nothing, I am calling the methods this way:

( < window > ).DatecsPrinter.listBluetoothDevices(.....)

**Comment by mithunvp** [comment]
Hi.. I am using this plugin in prod use now with Ionic 2, it works well. It works only on device. You need to pair the bluetooth printer & device then only printer shows up in listBluetoothDevices(). I used the Angular service on repo page.

**Comment by citerio** [comment]
Hey mithunvp, ok, perfect, yeah, I am testing my app on real device, yeah I read below a note that says about an angular/ionic service, but How Can I use that file?, there are many js files like this one ionic-angular.js

**Comment by mithunvp** [comment]
Use www/js/datecsprinter.service.js code and create service provider in Ionic 2 (PrinterService)

import { Injectable } from '@angular/core';
declare let DatecsPrinter:any;

@Injectable()
export class PrinterService { 

  public listBluetoothDevices(){
    return new Promise((resolve, reject) => {
        DatecsPrinter.listBluetoothDevices(
          function (success) {
            resolve(success);
          },
          function (error) {
            reject(error);
          });          
    });
  }
}

Then in any of Ionic 2 pages, inject PrinterService and write a method as below

LoadPrinterList(){
    this.printSer.listBluetoothDevices().then(result => {
      console.log(JSON.stringify(result));
      this.printerList = result;
    }).catch(err => {

    });
  }

Do the same for Connecting, Print, Disconnection.

Hope this helps !!

**Comment by citerio** [comment]
That's great man, thanks. What printer are you using?, I have a Zebra RW420 printer, so I don't know if this plugin will work with it because it's intended to DATECS printers I think.

**Comment by citerio** [comment]
I'm still having the issue, the methods are not being called (nothing is happening), I think the plugin is not being loaded properly, I installed it using:
cordova plugin add cordova-plugin-datecs-printer

I exactly did as you said, created a service and injected to a page. All other plugins work ok, they are perfectly loaded, but not this one.

**Comment by giorgiofellipe** [comment]
@citerio sorry for the delayed response, do you still having problems using this plugin on Ionic 2? As @mithunvp said, I'm using this in production with Ionic 2 too.

**Comment by bitwizer** [comment]
Here's the full class for ionic 2 (working fine for me)

```
import { Injectable } from '@angular/core';

declare let DatecsPrinter:any;

@Injectable()
export class PrinterService {

	public listBluetoothDevices(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.listBluetoothDevices( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public connect(address){
        return new Promise((resolve, reject) => {
            DatecsPrinter.connect( address, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public disconnect(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.disconnect( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public feedPaper(lines){
        return new Promise((resolve, reject) => {
            DatecsPrinter.feedPaper( lines, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public printText(text, charset = 'UTF-8'){
        // ISO-8859-1
        return new Promise((resolve, reject) => {
            DatecsPrinter.printText( text, charset, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public printSelfTest(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.printSelfTest( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public getStatus(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.getStatus( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public getTemperature(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.getTemperature( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public setBarcode(align, small, scale, hri, height){
        return new Promise((resolve, reject) => {
            DatecsPrinter.setBarcode( align, small, scale, hri, height, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public printBarcode(data, type = 73 ){
        return new Promise((resolve, reject) => {
            DatecsPrinter.printBarcode( type, data, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public printImage(image, width, height, align){
        return new Promise((resolve, reject) => {
            DatecsPrinter.printImage( image, width, height, align, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public drawPageRectangle(x, y, width, height, fillMode){
        return new Promise((resolve, reject) => {
            DatecsPrinter.drawPageRectangle( x, y, width, height, fillMode, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public drawPageFrame(x, y, width, height, fillMode, thickness){
        return new Promise((resolve, reject) => {
            DatecsPrinter.drawPageFrame( x, y, width, height, fillMode, thickness, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public selectPageMode(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.selectPageMode( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public selectStandardMode(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.selectStandardMode( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public setPageRegion(x, y, width, height, direction){
        return new Promise((resolve, reject) => {
            DatecsPrinter.setPageRegion( x, y, width, height, direction, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public printPage(){
        return new Promise((resolve, reject) => {
            DatecsPrinter.printPage( function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public write(bytes){
        return new Promise((resolve, reject) => {
            DatecsPrinter.write( bytes, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

    public writeHex(hex){
        return new Promise((resolve, reject) => {
            DatecsPrinter.writeHex( hex, function (success) {
                resolve(success);
            }, function (error) {
                reject(error);
            });
        });
    }

}
```

**Comment by pufanalexandru** [comment]
I'm having a similar issue.
I have this code:

`DatecsPrinter.listBluetoothDevices(
          function (devices) {
            DatecsPrinter.connect(devices[0].address, 
              function() {
                printText('Some text').then(
                  () => {console.log('it works')},
                  err => {console.log(err)}
                )
              },
              function(error) {
                console.log(JSON.stringify(error));
              }
            );
          },
          function (error) {
            console.log(JSON.stringify(error));
          }
      );`

The device is connecting and the text 'it works' is logged to the console, but the printer doesn't print the specified text. Am I missing something?

The device I use is a Datecs DPP-350C

**Comment by giorgiofellipe** [comment]
@pufanalexandru could you paste what is under `printText` function?

**Comment by rakeshravipati** [comment]
Hi giorgiofellipe,

Thanks for the Plugin.
I have implemented using Ionic2, code can be found @ <a href="https://github.com/rakeshravipati/ionic2bluetoothprinter">Repo</a>
I am able to list printers, Print sample Text and images. 
Could you please help with links or resources in implementing additional methods like printPage,  writeHex, write and other methods. 
Can I use html in print.
I have to print Qr code. I have gone through the methods available and I couldn't figure it out.  
Please Help Me. Sorry for my English.

**Comment by marquesgabriel** [comment]
Hello, i've installed the plugin and tried to use the class mentioned above.
But when it's running I receive the error `ReferenceError: DatecsPrinter is not defined`
Can someone help me?

**Comment by mithunvp** [comment]
It works only thru device. Please check it

**Comment by AldeirJampier** [comment]
Olá @giorgiofellipe a muito tempo tenho usado esse exelente plugin. Porém já me deparei com o problema do plugin não ser compátivel com aparelhos "Samsung", sim, parece ser estranho, mas nenhuma função do plugin, funciona em aparelhos samsung, os mesmo aplicativo copilado funciona em outros aparelho, e muito bem. Porém no samsung, quando se chama a função da api datecs, nada se faz, é como se o botão criado para chamar a função, fosse desativado nesse tipo de aparelho.

**Comment by giorgiofellipe** [comment]
@marquesgabriel only works on devices and after cordova is ready.

**Comment by giorgiofellipe** [comment]
@AldeirJampier estranho, utilizo em produção em tablets e smartphones samsung sem problemas, podes fornecer mais detalhes sobre o aparelho, versão do android e modelo da impressora? de preferência em outra issue!

**Comment by djasigner** [comment]
Boa noite, por favor como posso usar o printerPage ou se possível HTML eu não consigo formatar datas e moeda R$ real por exemplo.

**Comment by giorgiofellipe** [comment]
@djasigner por favor abra uma nova issue com todas as suas dúvidas
