### ISSUE TITLE
Tags definition

### ISSUE THREAD

**Issue by wailynnoo** [giorgiofellipe/cordova-plugin-datecs-printer#44]
Can i get the example code for Tags definition?

**Comment by giorgiofellipe** [comment]
```
window.DatecsPrinter.printText("{reset}{center}This is a {b}Test{/b}!", 'ISO-8859-1', 
    function() {
      alert('success!')
    }
  );
```

**Comment by wailynnoo** [comment]
@giorgiofellipe  Can i print html table with printText ? 
Thanks!

**Comment by giorgiofellipe** [comment]
It is not possible.

**Comment by vinay368** [comment]
Hi Please help Is there any method available which i can use for table content print in cordova-plugin-datecs-printer?
