### ISSUE TITLE
barcode not print

### ISSUE THREAD

**Issue by wailynnoo** [giorgiofellipe/cordova-plugin-datecs-printer#46]
I use below code to print barcode but nothing print. Not show any error. I already test with text it is work.
What am i wrong . Thnaks!
DatecsPrinter.listBluetoothDevices()
                      .then(function (addresses) {
                        return DatecsPrinter.connect(addresses[0]);
                      })
                      .then(function (success) {
                        return DatecsPrinter.printBarcode(75, '13132498746313210584982011487');
                      })
                      .then(function (success) {
                        return DatecsPrinter.disconnect();
                      })
                      .catch(function (error) {
                        alert(JSON.stringify(error));
                      });

**Comment by wailynnoo** [comment]
@giorgiofellipe  I also test with this.
It  do not print.

DatecsPrinter.listBluetoothDevices()
                      .then(function (addresses) {
                        return DatecsPrinter.connect(addresses[0]);
                      })
                      .then(function (success) {
                        return DatecsPrinter.setBarcode(1,1,2,2,5);
                      })
                      .then(function (success) {
                        return DatecsPrinter.printBarcode(75, '13132498746313210584982011487');
                      })
                      .then(function (success) {
                        return DatecsPrinter.disconnect();
                      })
                      .catch(function (error) {
                        alert(JSON.stringify(error));
                      });

**Comment by giorgiofellipe** [comment]
What is the printer model?

**Comment by wailynnoo** [comment]
I can print barcode when i change 73 for barcode type. 
Now I found the problem in printText.
It is always having 'I' character in the firstline.
How should i fix?

**Comment by giorgiofellipe** [comment]
Some people noticed this in some printers, it may should be a brand's specific implementation.

**Comment by giorgiofellipe** [comment]
Closing due not having any further info.
