### ISSUE TITLE
Problemas com impressão

### ISSUE THREAD

**Issue by alexandregncoelho** [giorgiofellipe/cordova-plugin-datecs-printer#5]
Boa tarde, Giorgio. Tudo bem? Estou com problemas aleatórios na impressão. Trabalho com impressão de fichas. Imprimo várias fichas por vez, de diferentes itens. Cada ficha é composta por apenas um conjunto de textos, esses com fontes menores e fontes maiores. Imprimo as fichas sem problemas e perfeitamente. Em algumas combinações de fichas, a impressora começa a imprimir e, de repente, no meio da impressão, a impressora para de imprimir e perde o pareamento com o aplicativo, mantendo apenas o pareamento com o tablet. Ou seja, ela para de imprimir no meio da impressão e a luz azul da impressora Datecs para de imprimir. Isso só acontece em algumas ocasiões e não existe um padrão para acontecer. Já viu algo parecido? Sabe como resolver isso ou debugar o problema com código de erros? Já testei com várias impressoras diferentes e vários tablets/celulares android e o erro continua. Acontece raramente mas acontece. Será que existe um bug relacionado a isso? Obrigado.

**Comment by giorgiofellipe** [comment]
Não cheguei a experienciar esse tipo de situação ainda, essa impressão é contínua? Digo, todas as fichas são impressas de uma única vez ou com intervalos?
O que deve ser observado é se alguma exceção é disparada no socket.

Se você conseguir mais informações posso tentar simular...

**Comment by alexandregncoelho** [comment]
Então. Funciona da seguinte forma: faço uma venda pelo meu aplicativo: 3
halls, 2 Tridents, 5 Chicletes. Ao finalizar a venda, imprimo 10 fichas em
uma única impressão, sendo 3 fichas de Halls, 2 fichas de Trident e 5
fichas de Chicletes. O que acontece é que, as vezes, raramente, era para
imprimir todas as 10, mas imprime 6 fichas e meia, por exemplo, pois no
meio da impressão da sétima ficha a impressora para de imprimir e perde o
paramento com o aplicativo, mantendo apenas o pareamento com o Tablet. Como
posso observar essa exceção disparada pelo socket?

Mais uma vez, muito obrigado.
Em 6 de jan de 2016 1:44 PM, "Giorgio Fellipe" <notifications@github.com>
escreveu:

**Comment by danielrgn** [comment]
@alexandregncoelho  Alexandre tudo joia? Você está conseguindo imprimir utilizando o plugin do @giorgiofellipe ?

Teria como você da um help, de como que você está fazendo para imprimir? Abraços!

**Comment by giorgiofellipe** [comment]
@alexandregncoelho @danielrgn 
Estarei fechando essa issue devido ao tempo sem feedback, se tiverem alguma dificuldade em utilizar o plugin ainda favor abrir nova issue, obrigado.
