### ISSUE TITLE
Central image

### ISSUE THREAD

**Issue by terrapin3** [giorgiofellipe/cordova-plugin-datecs-printer#52]
I never had a problem centering the image in the center, with code 1,  through the function:
.....
 window.DatecsPrinter.printImage(
          imageData, //base64
          canvas.width, 
          canvas.height, 
          1, 
......
Now the image is aligned to the left.

Congratulations on the plugin.
Hello

**Comment by giorgiofellipe** [comment]
Ensure you're not adding the plugin directly from this repository. Please use the NPM published version.

`cordova plugin add cordova-plugin-datecs-printer`

thanks!
