### ISSUE TITLE
barcode print MPR-III, not print MLP-2

### ISSUE THREAD

**Issue by tolgatelli** [giorgiofellipe/cordova-plugin-datecs-printer#53]
Hi,
I can print to bluetooth printer with cordova,ionic mobile application,
barcode or text is no problem,
I can print HPRT MPR-III,
but I can not print barcode with HPRT MLP-2 (I can print text MLP-2 but can not barcode),
I received "ok" message but dont print,
What do you think about that problem?

(my  test phone is samsung note 5)

**Comment by giorgiofellipe** [comment]
It's hard to figure out without having one.

Please provide printer docs.

**Comment by tolgatelli** [comment]
I write a web service, create image and I can print now, www.maksicar.com/barkod
also, can I do overline text? , I can print underline text but I dont know about overline..

**Comment by giorgiofellipe** [comment]
As far as I know it is not possible
