### ISSUE TITLE
Criar componente  em react native

### ISSUE THREAD

**Issue by AllanD1** [giorgiofellipe/cordova-plugin-datecs-printer#55]
@douglasjunior Esse é o código de impressão que eu tinha comentado na aula

**Comment by douglasjunior** [comment]
Legal, vou passar para uns amigos que estão trabalhando com isso no momento. cc @edvaldoszy @costabatista

**Comment by giorgiofellipe** [comment]
@AllanD1 https://guides.github.com/features/issues/
