### ISSUE TITLE
Instalação e utilização do cordova-plugin-datecs-printer no IONIC 2

### ISSUE THREAD

**Issue by djasigner** [giorgiofellipe/cordova-plugin-datecs-printer#56]

**Comment by giorgiofellipe** [comment]
@djasigner ?

**Comment by djasigner** [comment]
Desculpe Giorgio realmente fiz a pergunta e fiquei desesperado por uma solução, e terminei apagando para reformular e esqueci.
Consegui instalar o plugin usando IONIC 2, analisei a documentação com mais calma e realmente fiquei muito feliz em consegui instalar e imprimir, por ter pouco conhecimento em Angular 2 fiquei limitado porque o que quero imprimir envolvia um ngFor* e várias interpolações com pipes formatado datas e valores monetários em R$ 00.00 sacou foi difícil mas consegui.
Sem querer abusar muito é possível imprimir html formatado, minha impressora é a MTP-3 térmica.

**Comment by giorgiofellipe** [comment]
Sem problemas @djasigner.
Atualmente não é possível imprimir HTML mas você pode utilizar as [tags de formatação](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#tags-definition).
