### ISSUE TITLE
Tags definition (doubts)

### ISSUE THREAD

**Issue by talvespe** [giorgiofellipe/cordova-plugin-datecs-printer#58]
Hi guys, firstly I would like to thanks for this plugin.
Someone can provide some examples ...

How you are using these tags on yours templates ? 

Thanks in advance

**Comment by giorgiofellipe** [comment]
```
{reset}{center}This is a centered text! {br}
{reset}{b}And this is a bold left aligned text!{/b}
```

**Comment by talvespe** [comment]
works like a charm! Thanks @giorgiofellipe
