### ISSUE TITLE
Erro PhoneGap Build DatecsSDKWrapper.java

### ISSUE THREAD

**Issue by DaniloCruz** [giorgiofellipe/cordova-plugin-datecs-printer#59]
Error - Some official plugins have to be updated if using PhoneGap >= 4.0.0. Please upgrade the version of any plugins that may include the following file: DatecsSDKWrapper.java - You can fix this here

 cli-6.2.0 or cli-6.5.0

I got this error while compiling by PhoneGap Build.
A few days ago everything was normal.

Help

**Comment by DaniloCruz** [comment]
Log de Erro...

:generateDebugSources
:incrementalDebugJavaCompilationSafeguard
:compileDebugJavaWithJavac
:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:48: error: cannot find symbol
    private Printer mPrinter;
            ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:367: error: cannot find symbol
            mPrinter = new Printer(channel.getInputStream(), channel.getOutputStream());
                           ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:369: error: cannot find symbol
            mPrinter = new Printer(mProtocolAdapter.getRawInputStream(), mProtocolAdapter.getRawOutputStream());
                           ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:373: error: package Printer does not exist
        mPrinter.setConnectionListener(new Printer.ConnectionListener() {
                                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors
:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 7.742 secs
Error: /project/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Warning: AndroidManifest.xml already defines debuggable (in http://schemas.android.com/apk/res/android); using existing value in manifest.

/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:48: error: cannot find symbol
    private Printer mPrinter;
            ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:367: error: cannot find symbol
            mPrinter = new Printer(channel.getInputStream(), channel.getOutputStream());
                           ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:369: error: cannot find symbol
            mPrinter = new Printer(mProtocolAdapter.getRawInputStream(), mProtocolAdapter.getRawOutputStream());
                           ^
  symbol:   class Printer
  location: class DatecsSDKWrapper
/project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:373: error: package Printer does not exist
        mPrinter.setConnectionListener(new Printer.ConnectionListener() {
                                                  ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /project/src/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
    at ChildProcess.whenDone (/project/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by octaviofernands** [comment]
Same error here. I Just installed the plugin.

**Comment by riadapsis** [comment]
Also facing the same error. Anyone have any alternative of it? I need to print some UTF-8 charecter at a Cashino PTP-II thermal Bluetooth printer.

**Comment by DaniloCruz** [comment]
Não consegui resolver ainda. A poucos dias estava tudo funcionando normal. Agora esta apresentando esse problema... Precisa ajustar alguma coisa nos arquivos java. Os erros estão ai no log, mas não entendo nada de java.

**Comment by giorgiofellipe** [comment]
@DaniloCruz @octaviofernands @riadapsis fixed on v0.7.4, thanks!
