### ISSUE TITLE
Tutorial ou Exemplo

### ISSUE THREAD

**Issue by claytonultrago** [giorgiofellipe/cordova-plugin-datecs-printer#6]
Olá. Tem alguma página com tutorial ou exemplos de como usar o plugin para impressão no cordova com impressora datecs?

**Comment by giorgiofellipe** [comment]
@claytonultrago ainda não, vou providenciar instruções detalhadas em breve...

**Comment by fignewton** [comment]
@giorgiofellipe I would also like more detailed documentation or code samples on how to use this plugin. I'm very interested in it.

**Comment by danielrgn** [comment]
Olá @giorgiofellipe parabéns pela iniciativa! Cara também estou com dúvidas de como realizar uma impressão pela impressora datecs utilizando o cordova!

Abraços!

**Comment by giorgiofellipe** [comment]
@claytonultrago @danielrgn estou meio sem tempo pra desenvolver um tutorial mais elaborado, mas tentarei dar uma luz à vocês rapidamente por aqui mesmo.
@fignewton 

The first thing that you must know is that the plugin is available through this variable `window.DatecsPrinter`.

So, there's a lot of functions that you can call to execute each operation and perform the printer actions, these are the most important ones (you can see all on printer.js file):

_(every function accept at least two parameters, and they're the last ones: onSuccess function and onError function)_

- listBluetoothDevices(): will give you a list of all the already previously paired bluetooth devices
- connect(address): this will establish the bluetooth connection with the selected printer (you need pass the `address` attribute of the selected device)
- feedPaper(lines): this will "print" blank lines
- printText(text): will print the text respecting tags definition


```javascript
window.DatecsPrinter.listBluetoothDevices(
  function (devices) {
    window.DatecsPrinter.connect(devices[0].address, printSomeTestText);
  },
  function (error) {
  }
);

function printSomeTestText() {
  window.DatecsPrinter.printText("Print Test!");
}
```

**Comment by fignewton** [comment]
@giorgiofellipe Thank you so much for this! Actually I had already figured out to use window.DatecsPrinter after a lot of trial and error, but your code snippet above makes it much clearer how to use.

You should add these instructions/code snippet to the Readme. You may save a life. Thank you for the plugin too!

**Comment by giorgiofellipe** [comment]
@fignewton already did this. Thanks!

**Comment by danielrgn** [comment]
@giorgiofellipe você ja experimentou utilizar esse plugin juntamente com ionic?

**Comment by giorgiofellipe** [comment]
@danielrgn eu utilizo ele em um projeto comercial que utiliza ionic!

**Comment by danielrgn** [comment]
entendi @giorgiofellipe , então da pra utilizar seu plugin normalmente com o ionic, e é da maneira que você mostrou acima. Cara muito obrigado mesmo por enquanto, e mais uma vez parabéns pela iniciativa! Você vai longe! Abraços

**Comment by giorgiofellipe** [comment]
@danielrgn obrigado Daniel! Então, com o Angular você precisa criar um wrapper, por trabalhar de forma assíncrona você precisa encaixar o plugin no fluxo de atualização do Angular (digest cycle). 
Se você já possui alguma experiência com angular vai captar fácil a ideia, se não tem vou explicar sucintamente: a ideia é simples, todo processamento assíncrono, realizado por biblioteca externa deve ser envolvida em uma Promise (`$q`).

Exemplo:
```
angular.module('app.service.datecsprinter', [])
    .factory('DatecsPrinter', 
  function($q, $window) {
    var listBluetoothDevices = function () {
      var deferred = $q.defer();

      $window.DatecsPrinter.listBluetoothDevices(
        function (success) {
          deferred.resolve(success);
        },
        function (error) {
          deferred.reject(error);
        }
      );

      return deferred.promise;
    };

  return {
    listBluetoothDevices: listBluetoothDevices 
  };
});
```

**Comment by danielrgn** [comment]
Compreendo @giorgiofellipe , obrigado pelo exemplo!

Amigo, você não tem nenhum exemplo demo completo utilizando o Ionic? A impressora datecs que estou utilizando é a DPP-250, não sei se é ela ou algo que estou tentando fazer que não da certo.

Obrigado.

**Comment by danielrgn** [comment]
Se puder enviar para meu e-mail (danielrgn@hotmail.com), algo bem simples, como a chamada do index, do app.js junto com uma chamada da controller e da factory de conexão com a datecs.

**Comment by giorgiofellipe** [comment]
@danielrgn É o mesmo modelo que uso. Não há nenhum segredo na utilização, seguindo as orientações acima funcionará sem problemas (lembrando que o device deve estar previamente pareado).
Se tiver alguma dificuldade abra uma issue nova para discutirmos melhor.

**Comment by jdiiego** [comment]
Hello, I need an example to be able to print an image.
I have a mistake:
{"errorCode":11,"message":"Error printing image","exception":"BufferedOutputStream is closed"}

**Comment by giorgiofellipe** [comment]
@jdiiego https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#example

**Comment by jdiiego** [comment]
not problem with RGB images or do I give a monochrome image?

**Comment by giorgiofellipe** [comment]
@jdiiego generally there is no problem with colors, it will burn as the color intensity. Printers do not recognize transparency...

**Comment by jeancss02** [comment]
@giorgiofellipe boa tarde é possivel utilizar este plugin em aplições mobile ?
Se possivel poderia me dá um pequeno exemplo, gostaria de gerar pdf para imprimir na DPP - 350.

Email: jeancss01@gmail.com


Muito obrigado!

**Comment by jeancss02** [comment]
Neste caso um aplicativo Android :)

**Comment by giorgiofellipe** [comment]
@jeancss02 sim é possível, mas no caso de uma aplicação nativa não faz muito sentido. A intenção deste é criar uma ponte entre javascript e a biblioteca nativa da Datecs, você pode utilizar diretamente esta biblioteca, bastando importa-la como dependência do seu projeto...

**Comment by jeancss02** [comment]
Foi isto que eu fiz, muito Obrigado!

Forte Abraço (:

**Comment by djasigner** [comment]
Excelente esta biblioteca ja instalei e funcionou perfeitamente, só estou perdido um pouco porque não sei como imprimir um texto dinâmico.
Gostaria de um exemplo ou um link, qualquer dica será muito apreciada.

Muito obrigado.
