### ISSUE TITLE
No response on large image

### ISSUE THREAD

**Issue by riadapsis** [giorgiofellipe/cordova-plugin-datecs-printer#61]
When I am trying to print a canvas of 350X600, then it always show success message but nothing print on my printer. But if I reduce the canvas size to 200X150, it works. Actually I need to print a memo which may have over 30 line and I am using the local language (Bangla) which is not actually supported by printer. So with the drawing the text inside a canvas it can be done too easily. But now stuck with the size. I am using Cashino PTP-II(58MM) printer.

**Comment by giorgiofellipe** [comment]
It may be a memory printer limitation, not the plugin itself.
