### ISSUE TITLE
Having issue on printing Chinese Char

### ISSUE THREAD

**Issue by jenqtat** [giorgiofellipe/cordova-plugin-datecs-printer#63]
Hi,
I able to use this plugin for P80A Bluetooth printer. However I unable to print Chinese Char even set the charset as UTF-8. Any advise or guidance ?

**Comment by riadapsis** [comment]
I am also facing same issue with Bengali character. Resolved with canvas image printing but failed to print a large canvas.. Looking for a solution to print unicode character.

**Comment by nok32** [comment]
Any solution to print unicode character?

**Comment by csleeds** [comment]
> Hi,
> I able to use this plugin for P80A Bluetooth printer. However I unable to print Chinese Char even set the charset as UTF-8. Any advise or guidance ?

use GB2312 or GB18030 for chinese character
