### ISSUE TITLE
Printer not prining the barcode and QR code

### ISSUE THREAD

**Issue by nagaraju7752** [giorgiofellipe/cordova-plugin-datecs-printer#64]
window.DatecsPrinter.printBarcode(
              72, //here goes the barcode type code
              '13132498', //your barcode data
              function() {
                alert('success!');
                
              },
              function(error) {
                alert(JSON.stringify(error));
              }
            );

I am using this code in **Sunmi v1 wireless thermal  pos printer**.but it is not printing getting empty paper. how to resolve this.

**Comment by nagaraju7752** [comment]
If anyone knows how to print qrcode  using cordova-plugin-datecs-printer.Please let me know

**Comment by jeremy-saidani** [comment]
Hi !

I'm using https://github.com/zenozeng/node-yaqrcode to generate base64 qr code
` var imageBase64 = Yaqrcode(yourdata, { size: 300, errorCorrectLevel: 'H' });
      imageBase64 = imageBase64.replace(/^data:image\/(png|jpg|jpeg|gif);base64,/, "");`
` window['DatecsPrinter'].printImage(imageBase64, 300, 300, 1, successCallback, errorCakkback)`

It works perfectly for me !

**Comment by giorgiofellipe** [comment]
@nagaraju7752 @jeremy-saidani this plugin was updated and it is now able to print QRCodes, please check out the version 0.8.2.

**Comment by nagaraju7752** [comment]
Thank you.

**Comment by jeremy-saidani** [comment]
I tried but the printQRCode function doesn't work for me
The data string is printed instead of the qr code image

**Comment by giorgiofellipe** [comment]
@jeremy-saidani what is your printer model? It may not work on all models, but I've added a workaround for these cases, please see the second example [here](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#print-qrcode-example).
