### ISSUE TITLE
Error on cordova 8.0.0

### ISSUE THREAD

**Issue by carlosfred** [giorgiofellipe/cordova-plugin-datecs-printer#75]
Bom dia Fellipe, poderia me ajudar com este erro, parece que versão 8.0.0 do cordova não tem a pasta res dentro de platforms\android

cp: copyFileSync: could not write to dest file (code=ENOENT):E:\Apps\guiasdosom\v5\platforms\android\res\xml\config.xml

Parsing E:\Apps\guiasdosom\v5\platforms\android\res\xml\config.xml failed
(node:9000) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open 'E:\Apps\guiasdosom\v5\platforms\android\res\xml\config.xml'
(node:9000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by carlosfred** [comment]
Só pra melhorar a sua análise, reinstalei o cordova 7.0.0 e nesta versão o plugin funciona sem problemas.

**Comment by giorgiofellipe** [comment]
Acredito ser um problema do Ionic CLI que ainda não se adaptou à nova estrutura do cordova 8.
Acompanhe a discussão neste [tópico](https://github.com/ionic-team/ionic/issues/13702), nele vc pode encontrar alguns _workarounds_ tb.

Caso seja verificada a necessidade de alguma atualização no plugin basta comentar aqui que reabrirei.

Obrigado.

**Comment by carlosfred** [comment]
acho mesmo que é um problema do cli, mas não estou usando o ionic, só o cordova mesmo.

**Comment by giorgiofellipe** [comment]
@carlosfred ah, falha minha. Então provável que seja do cordova cli...

**Comment by marcellopato** [comment]
Então, qual a solução para o problema?

**Comment by carlosfred** [comment]
Rapaz, eu usei a versão 7 do cordova e funcionou sem problemas

**Comment by marcellopato** [comment]
Obrigado @carlosfred . E como eu desinstalo a versão 8 e de onde baixo a versão 7, por favor?

**Comment by marcellopato** [comment]
@carlosfred relaxa, já googlei e já re instalei a 7. Agora é ver se roda.
Obrigado cara!

**Comment by carlosfred** [comment]
Valeu Marcelo. abraços
