### ISSUE TITLE
Build Failed! :/

### ISSUE THREAD

**Issue by leonardofmed** [giorgiofellipe/cordova-plugin-datecs-printer#79]
Estou a 2 dias tentando consertar isso, mas não acho jeito. Antes de instalar o plugin o app estava funcionando normalmente, pode me dar uma luz por favor?

Erro:

:app:compileDebugJavaWithJavac
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:3: error: package com.datecs.api.biometric does not exist

import com.datecs.api.biometric.TouchChip;

                               ^

/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1357: error: cannot find symbol

    public TouchChip getTouchChip() {

           ^

  symbol:   class TouchChip

  location: class Printer

/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:41: error: package com.datecs.api does not exist
import com.datecs.api.BuildInfo;
                     ^

/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:42: error: package com.datecs.api.printer does not exist
import com.datecs.api.printer.ProtocolAdapter;
                             ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:47: error: cannot find symbol
    private ProtocolAdapter mProtocolAdapter;
            ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist
    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {
                                 ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol

        TouchChip instance = new TouchChip() {

        ^

  symbol:   class TouchChip

  location: class Printer

/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol
        TouchChip instance = new TouchChip() {
                                 ^
  symbol:   class TouchChip
  location: class Printer
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist

    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {

                                                                                        ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:360: error: cannot find symbol

        mProtocolAdapter = new ProtocolAdapter(inputStream, outputStream);

                               ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: package ProtocolAdapter does not exist
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);

                                 ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: cannot find symbol
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);
                                                                                ^
  symbol:   variable ProtocolAdapter
  location: class DatecsSDKWrapper
Note: /home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: /home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses unchecked or unsafe operations.

Note: Recompile with -Xlint:unchecked for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
 FAILED
27 actionable tasks: 7 executed, 20 up-to-date
(node:31565) UnhandledPromiseRejectionWarning: Error: /home/leo/printer04/platforms/android/gradlew: Command failed with exit code 1 Error output:
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:3: error: package com.datecs.api.biometric does not exist
import com.datecs.api.biometric.TouchChip;
                               ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1357: error: cannot find symbol
    public TouchChip getTouchChip() {
           ^
  symbol:   class TouchChip
  location: class Printer
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:41: error: package com.datecs.api does not exist
import com.datecs.api.BuildInfo;
                     ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:42: error: package com.datecs.api.printer does not exist
import com.datecs.api.printer.ProtocolAdapter;
                             ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:47: error: cannot find symbol
    private ProtocolAdapter mProtocolAdapter;
            ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist
    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {
                                 ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol
        TouchChip instance = new TouchChip() {
        ^
  symbol:   class TouchChip
  location: class Printer
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/Printer.java:1358: error: cannot find symbol
        TouchChip instance = new TouchChip() {
                                 ^
  symbol:   class TouchChip
  location: class Printer
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:61: error: package ProtocolAdapter does not exist
    private final ProtocolAdapter.PrinterListener mChannelListener = new ProtocolAdapter.PrinterListener() {
                                                                                        ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:360: error: cannot find symbol
        mProtocolAdapter = new ProtocolAdapter(inputStream, outputStream);
                               ^
  symbol:   class ProtocolAdapter
  location: class DatecsSDKWrapper
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: package ProtocolAdapter does not exist
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);
                                 ^
/home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java:364: error: cannot find symbol
            final ProtocolAdapter.Channel channel = mProtocolAdapter.getChannel(ProtocolAdapter.CHANNEL_PRINTER);
                                                                                ^
  symbol:   variable ProtocolAdapter
  location: class DatecsSDKWrapper
Note: /home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /home/leo/printer04/platforms/android/app/src/main/java/com/giorgiofellipe/datecsprinter/DatecsSDKWrapper.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
12 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
    at ChildProcess.whenDone (/home/leo/printer04/platforms/android/cordova/node_modules/cordova-common/src/superspawn.js:169:23)
    at ChildProcess.emit (events.js:160:13)
    at maybeClose (internal/child_process.js:943:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
(node:31565) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:31565) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by giorgiofellipe** [comment]
Tente remover os plugins e adiciona-los novamente

**Comment by leonardofmed** [comment]
Fiz isso para todos os plugins instalados e o mesmo erro persiste.

**Comment by giorgiofellipe** [comment]
Tente remover a plataforma android e adicionar novamente.

**Comment by leonardofmed** [comment]
Isso retorna o erro da outra issue que eu postei, relacionado ao arquivo config.xml. Li também o issue que você me passou, pelo jeito não acharam solução ainda. Vou tentar fazer um downgrade no cordova ver se resolve algo.

**Comment by leonardofmed** [comment]
Fiz downgrade no cordova pro 6.5 e o erro sumiu. Build Successful, Launch Success.
Muito obrigado pela ajuda!
