### ISSUE TITLE
Inicializando um projeto Ionic com o cordova-plugin-datects-printer

### ISSUE THREAD

**Issue by danielrgn** [giorgiofellipe/cordova-plugin-datecs-printer#8]
@giorgiofellipe estou com dúvidas e problemas em relação a escuta dos aparelhos com o broadcaster.

Segundo suas instruções para cordova:

window.broadcaster.addEventListener( "DatecsPrinter.connectionStatus", function(e) {
  if (e.isConnected) {
    //do something
  }
});

Porém para o ionic, eu coloquei:

$window.broadcaster.addEventListener( "DatecsPrinter.connectionStatus", function(e) {
  if (e.isConnected) {
    //do something
  }
});

Porém, quando coloco essa parte no ionic, depois de ter instalado o seu plugin e o plugin do cordova broadcaster, da o seguinte erro:

TypeError: Cannot read property 'addEventListener' of undefined

Poderia me dar um help?

Grato!!!!!

**Comment by giorgiofellipe** [comment]
1. O plugin `cordova-plugin-broadcaster` não funciona no browser

2. Certifique-se de que está utilizando o broadcaster somente após o carregamento completo da aplicação.
```javascript
$ionicPlatform.ready(function() {
  $window.broadcaster.addEventListener("DatecsPrinter.connectionStatus", function (e) {
  });
});
```

**Comment by danielrgn** [comment]
app = angular.module('starter', ['ionic', 'starter.controllers', 'starter.services']);

app.run(function($ionicPlatform, $window) {
  $ionicPlatform.ready(function() {

    $window.broadcaster.addEventListener("DatecsPrinter.connectionStatus", function (e) {
      if (e.isConnected) {
        alert('Conectado');
      }else{
        alert('Falha');
      }
    });

    if(window.cordova && window.cordova.plugins.Keyboard) {
      // Hide the accessory bar by default (remove this to show the accessory bar above the keyboard
      // for form inputs)
      cordova.plugins.Keyboard.hideKeyboardAccessoryBar(true);

      // Don't remove this line unless you know what you are doing. It stops the viewport
      // from snapping when text inputs are focused. Ionic handles this internally for
      // a much nicer keyboard experience.
      cordova.plugins.Keyboard.disableScroll(true);
    }
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
   
  });
});

**Comment by giorgiofellipe** [comment]
Não tenho certeza se o broadcaster funciona no Ionic View, testou em algum device real?

**Comment by danielrgn** [comment]
@giorgiofellipe , realizei o build dele para android, para testar no meu device, e não apareceu nenhum alert, possivelmente deve ta com algum erro de js :/ (estou com bluetooth ligado)

**Comment by danielrgn** [comment]
Realmente, não esta funcionando :(

@giorgiofellipe , você não poderia tentar montar um projeto basico funcional, que você ja tenha testado e funcionado ai? 

Agradeceria muito!

Abraços

**Comment by giorgiofellipe** [comment]
@danielrgn posso fazer sim, mas somente hoje à noite...

Por acaso você chegou a baixar o app da Datecs que testa a conexão e impressão? Com ele está funcionando?

**Comment by danielrgn** [comment]
Obrigado @giorgiofellipe 

Já sim, ja testei com o app da datecs e também outros apps que baixei na play store.

**Comment by danielrgn** [comment]
@giorgiofellipe , você conseguiu montar o projeto? Se puder mandar para o danielrgn@hotmail.com

**Comment by giorgiofellipe** [comment]
@danielrgn https://github.com/giorgiofellipe/cordova-plugin-datecsprinter-example
desculpe a demora!

**Comment by danielrgn** [comment]
@giorgiofellipe  imagina cara tranquilo, muito obrigado, agora sim ficou bem exemplificado!

Como que você fez para testar se estava funcionando ou não, por exemplo, se algo não da certo, e depois que você ja fez o build do apk, como que você ve se teve algum problema no console.log?

Eu não estou conseguindo fazer esse debug :/

Estou testando em um tablet android 4.1, pareado na impressora Datecs DPP 250. Criei um novo projeto, coloquei todo o exemplo que você me passou, fiz um ionic platform android, e depois um ionic build android. Depois disso peguei o apk na pasta android/bin/MainActivity-debug.apk, e tentei testar aqui e não foi :(

Muito obrigado @giorgiofellipe

**Comment by giorgiofellipe** [comment]
@danielrgn pra debugar eu uso run com live reload, console logs e server logs `ionic run -lcs android`

**Comment by danielrgn** [comment]
@giorgiofellipe obrigado pelo fast reply!

**Comment by djasigner** [comment]
Boa tarde, Ajuda por favor! Estou com duvidas na instalação e utilização deste plugin ( **cordova-plugin-datects-printer** ) no ionic 2, tenho uma aplicação que gerar resultados de jogos e gostaria de imprimir em uma impressora térmica MTP-Printer.
