### ISSUE TITLE
Alert: undefined

### ISSUE THREAD

**Issue by leonardofmed** [giorgiofellipe/cordova-plugin-datecs-printer#82]
Fiz um app blank, coloquei um botão que quando apertado rodava a função postada no README. Quando aperto o botão de imprimir abre uma janelo procurando a impressora e outra com um erro "Alert undefined". Fiz outro app com a função mais simples e o mesmo erro acontece. 
##
home.ts:

import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController) {

  }

  printItem(){
  (<any>window).DatecsPrinter.listBluetoothDevices(
  function (devices) {
    (<any>window).DatecsPrinter.connect(devices[0].address, 
      function() {
        printSomeTestText();
      },
      function() {
        alert(JSON.stringify(Error));
      }
    );
  },
  function (error) {
    alert(JSON.stringify(Error));
  }
);

function printSomeTestText() {
  (<any>window).DatecsPrinter.printText("Print Test!", 'ISO-8859-1', 
    function() {
      printMyImage();
    }
  );
}

function printMyImage() {
  var image = new Image();
  image.src = 'img/some_image.jpg';
  image.onload = function() {
      var canvas = document.createElement('canvas');
      canvas.height = 100;
      canvas.width = 100;
      var context = canvas.getContext('2d');
      context.drawImage(image, 0, 0);
      var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove mimetype
      (<any>window).DatecsPrinter.printImage(
          imageData, //base64
          canvas.width, 
          canvas.height, 
          1, 
          function() {
            printMyBarcode();
          },
          function(error) {
              alert(JSON.stringify(Error));
          }
      )
  };
}

function printMyBarcode() {
  (<any>window).DatecsPrinter.printBarcode(
    75, //here goes the barcode type code
    '13132498746313210584982011487', //your barcode data
    function() {
      alert('success!');
    },
    function() {
      alert(JSON.stringify(Error));
    }
  );
}

  }

}
##

![screenshot_2018-02-14-19-50-04](https://user-images.githubusercontent.com/33374703/36234231-031cc12a-11d1-11e8-9864-4410e6ac45da.png)
![screenshot_2018-02-14-19-50-11](https://user-images.githubusercontent.com/33374703/36234232-034f705c-11d1-11e8-9061-f3c28f287d2b.png)

**Comment by giorgiofellipe** [comment]
Não está relacionado ao plugin, há erros em seu código.

**Comment by leonardofmed** [comment]
Desculpa a ignorância, acabei de começar com o Ionic e passei do "hello world" para a implementação de plugins e utilzação geral. Poderia me indicar o erro ou algo que deveria ter sido implementado e que não foi?
Dei uma lida em todos os outros issues pra ver se não encontrava outro exemplo, mas não achei nada do tipo.
Tentei implementar algo tipo [isso](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/43) e [isso](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/46), mas não deu certo também.
Não achei o arquivo www/js/datecsprinter.service.js que é mencionado [nessa issue](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/42), então não consegui aplicar também.
E [nessa issue](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/69) não entendi onde deveria criar esse service que você mencionou.

**Comment by giorgiofellipe** [comment]
Você está tentando fazer o JSON.stringify em uma variável que não existe, o callback de error não está recebendo o parâmetro error que vc quer imprimir no alert.

**Comment by leonardofmed** [comment]
Muito obrigado pela atenção! Fui atrás de como poderia implementar essas funções e vi que o ionic trabalha com providers. Fiz um provider e inseri o seu exemplo do issue 69 que linkei antes. Na página inseri o seguinte código, baseado no exemplo do comentário do issue 42:

```
import { Component } from '@angular/core';
import { NavController } from 'ionic-angular';
import { Print } from '../../providers/print/print';

@Component({
  selector: 'page-home',
  templateUrl: 'home.html'
})
export class HomePage {

  constructor(public navCtrl: NavController, private print: Print) {

  }

  printItem(){
  	this.print.listBluetoothDevices().then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });

    this.print.connect('00:02:5B:B4:7C:3A').then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });

    this.print.printText("Print Test!", 'ISO-8859-1').then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });

    this.print.feedPaper(20).then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });

    this.print.disconnect().then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });
    
  }

}
```
Isso me trouxe resultados positivos, muito obrigado mesmo por isso. A única função que não funcionou corretamente foi a do feedPaper, que não faz nada, apesar de mostrar no console.log a mensagem de "OK".

Como está a função no provider:

```
feedPaper(lines: Number): Promise<any> {
    return new Promise<any>((resolve, reject) => {
      this.win.DatecsPrinter.feedPaper(lines, (success) => resolve(success), (error) => reject(error));
    });
  }
```

**Comment by giorgiofellipe** [comment]
Qual o modelo da impressora?

**Comment by leonardofmed** [comment]
MPT III - Leopardo A7

**Comment by leonardofmed** [comment]
Alguma sugestão?

**Comment by giorgiofellipe** [comment]
Não tenho mais esse modelo para testar, mas ele já foi testado anteriormente e funcionou perfeitamente. Infelizmente não consigo te ajudar.
