### ISSUE TITLE
What is the unit of measurement used to width and height in the method printImage?

### ISSUE THREAD

**Issue by renatosousafilho** [giorgiofellipe/cordova-plugin-datecs-printer#83]
I want to know which is the unit of measurement used to width and height in the method printImage. Pixel, millimeter or anything else?

**Comment by giorgiofellipe** [comment]
Pixels.

**Comment by renatosousafilho** [comment]
@giorgiofellipe eu comentei nessa issue aqui o problema que to tendo com o plugin para imprimir um conteudo HTML dinâmico. Pode me dar uma força?

**Comment by giorgiofellipe** [comment]
Não entendi qual o seu problema, podes detalhar aqui?

**Comment by renatosousafilho** [comment]
Eu tava tentando imprimir um conteúdo HTML usando o html2canvas e a impressão estava parando na metade. Consegui dar um jeito, depois posto aqui a solução.
