### ISSUE TITLE
Cannot read property 'listBluetoothDevices' of undefined  in  datecs printer

### ISSUE THREAD

**Issue by Gunasekaran15** [giorgiofellipe/cordova-plugin-datecs-printer#84]
I have  used  your  example  in my cordova project  for  detecting the epson TM-P20  printer  but  it shows the following error:

Cannot read property 'listBluetoothDevices' of undefined

**Comment by giorgiofellipe** [comment]
Pay attention to instructions on this project's README.
Also, taking a look at the other issues you've opened  I guess it has been resolved.
