### ISSUE TITLE
Unable to print the QRCode and printing the text only. 

### ISSUE THREAD

**Issue by Gunasekaran15** [giorgiofellipe/cordova-plugin-datecs-printer#86]
Unable to print the QRCode and printing the text only. kindly do the needful
window.DatecsPrinter.listBluetoothDevices(
function (devices) {
window.DatecsPrinter.connect(devices[0].address,
function() {
// printQRCode();
printMyQRCode();
},
function() {
alert(JSON.stringify(error));
}
);
},
function (error) {
alert(JSON.stringify(error));
}
);

function printMyQRCode() {
window.DatecsPrinter.printQRCode(
4, // qr code size
4, // qr code error correction
'http://www.datecs.bg', // barcode data
function() {
alert('success!');
},
function() {
alert(JSON.stringify(error));
}
);
}

**Comment by giorgiofellipe** [comment]
What is your printer model?
Also please use markdown code format.

**Comment by Gunasekaran15** [comment]
EPSON TM-P20  thermal printer

**Comment by simo154** [comment]
did you managed to print the QR code using Datecs printer?
