### ISSUE TITLE
How to apply {br} tag in text printing

### ISSUE THREAD

**Issue by Gunasekaran15** [giorgiofellipe/cordova-plugin-datecs-printer#87]
I want print texts next next lines.so,please guide me how to apply {br} and all other  tags in the code.

**Comment by giorgiofellipe** [comment]
```javascript
window.DatecsPrinter.printText("First line... {br}Second line.", 'ISO-8859-1', success, error);
```

**Comment by Gunasekaran15** [comment]
I tried the above example but it does't  print text in second line,It  print {br} with that text in single line.

**Comment by giorgiofellipe** [comment]
So your printer model does not support tags. You should send separate commands and feed paper accordingly with your own.

**Comment by remiglobal** [comment]
sometimes u need to parse your variables correctly and just use .toString()
accordingly.

**Comment by ezequiel88** [comment]
In the IONIC 3 work in device MPT-II

`<button ion-button (click)="printText('AUTO PARKING\nFone: 54 999956591\nPlaca: AIB1417 \n\n\n')" block>Imprimir</button>`

Use \n for new line
