### ISSUE TITLE
How i use this code in ionic???

### ISSUE THREAD

**Issue by pedroCirilo** [giorgiofellipe/cordova-plugin-datecs-printer#88]
Need your help!!

**Comment by giorgiofellipe** [comment]
You can use it directly form global var window.DatecsPrinter or wrap it into an angular service.

If you're using Ionic v1 I have an example [here](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer#angular--ionic).
If you're using Ionic 2+ you, check [this](https://github.com/giorgiofellipe/cordova-plugin-datecs-printer/issues/69#issuecomment-350059665).

**Comment by pedroCirilo** [comment]
pqp vc é brasileiro kkkkk
