### ISSUE TITLE
Image printing

### ISSUE THREAD

**Issue by ivangutierrezr** [giorgiofellipe/cordova-plugin-datecs-printer#9]
Hi, i'm trying to print an image, but i don't know how it works properly, can you help me with some example? I'm doing this with simple javascript

Hola, estoy tratando de imprimir una imagen pero no se como hacerlo funcionar, puedes ayudarme con algún ejemplo de como implementarlo? Estoy usando solamente Javascript

Pd: si no hablas ingles, puedes contestarme en español o portugués que yo puedo entender algo.

**Comment by ivangutierrezr** [comment]
This is my code:

function imprimirCodigodeBarras() {
              window.DatecsPrinter.printImage("img/Logo.jpg",100,200,"{center}",function ()
                {alert("imprimiendo");},
                function (error){ 
                    alert(error); 
                });
            }

When I wxecute this, i get an error massage that says: "JSON error". Do you know why?

**Comment by giorgiofellipe** [comment]
The method `printImage` expects the first parameter as the base64 of the image. You can easily achieve this by doing it this way:

```javascript
var image = new Image();
image.src = 'img/some_image.jpg';
image.onload = function() {
    var canvas = document.createElement('canvas');
    canvas.height = 100;
    canvas.width = 100;
    var context = canvas.getContext('2d');
    context.drawImage(image, 0, 0);
    var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
    window.DatecsPrinter.printImage(
        imageData, 
        canvas.width, 
        canvas.height, 
        1, 
        function() {
            alert('success!');
        },
        function() {
            alert('error!');
        }
    )
};
```

**Comment by ivangutierrezr** [comment]
Hi @giorgiofellipe Thank you so much! could you gave a example for barcode please! is the last thing that I need. I appreciate this a lot!

**Comment by giorgiofellipe** [comment]
@ivangutierrezr here you go

```javascript
window.DatecsPrinter.printBarcode(
  75, //here goes the barcode type code, you can find this on README
  '13132498746313210584982011487', //your barcode data
  function() {
    alert('success!');
  },
  function() {
    alert('error!');
  }
);
```

**Comment by ivangutierrezr** [comment]
@giorgiofellipe Thank you so much man! please don't close this issue yet. everything works ok for me right now.

**Comment by ivangutierrezr** [comment]
@giorgiofellipe I'm sorry, i have a question. printImage() just works if the image is in a folder? it doesn't work if i have a image in a <img> or <canvas> tag?. Thank you.

**Comment by giorgiofellipe** [comment]
@ivangutierrezr it works on any way, you just need to get the base64 of the image and pass it to `printImage` method

**Comment by ivangutierrezr** [comment]
@giorgiofellipe thank you, i'll try.

**Comment by ivangutierrezr** [comment]
@giorgiofellipe i will pass you my code:

i have a img tag like this:

`<img id="codigoDeBarrasFactura" width="300px" height="100px>"`

I have a button that calls this function:

```
function imprimirFactura()
{
	//guardarDatosFacturaUsuariosServicios(); 

  	window.DatecsPrinter.listBluetoothDevices(
        function (devices) {
            window.DatecsPrinter.connect(devices[0].address, imprimirImagenDePrueba);
        },
        function (error) {
        	swal(JSON.stringify(error)); 
        }
    );
}

function imprimirImagenDePrueba() 
{
	var imagen = document.getElementById("codigoDeBarrasFactura");
	var imageData = imagen.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, "")
    window.DatecsPrinter.printImage(
    imageData, 
    canvas.width, 
    canvas.height, 
    1, 
    function() 
    {
		imprimirEncabezado();
    },
    function (error) {
        swal(JSON.stringify(error)); 
    });
}

```
what's wrong?

**Comment by ivangutierrezr** [comment]
@giorgiofellipe the image is codebar. i'm doing this because the codebar printer with the plugin wasn't compleate, it was a part from the barcode that doesn't appear because the barcode was bigger than the paper width. I don't know how setBarCode() function works.

**Comment by giorgiofellipe** [comment]
**setBarcode**

```java
public void setBarcode(int align,
                       boolean small,
                       int scale,
                       int hri,
                       int height)
```
Sets the various barcode parameters.
If align is negative, or scale < 2 || scale > 4 , or hri is negative, or height < 1 || height > 255, then a IllegalArgumentException is thrown.

**Parameters:**
_align_ - the align of barcode. See the ALIGN_* constant field values.
_small_ - the HRI code font size.
_scale_ - the scale factor of barcode, value between 2 and 4.
_hri_ - the HRI text position of barcode. See the HRI_* constant field values below.
_height_ - the height of barcode, value between 1 and 255.

```java
public static final int	HRI_ABOVE	= 1
public static final int	HRI_BELOW	= 2
public static final int	HRI_BOTH	= 3
public static final int	HRI_NONE	= 0
```

**Comment by ivangutierrezr** [comment]
@giorgiofellipe Ok, so, i have to setBarcode First and printBarCode after, right?

**Comment by giorgiofellipe** [comment]
@ivangutierrezr yes

**Comment by ivangutierrezr** [comment]
@giorgiofellipe Thank you so much, everything is perfect!. You must put this information on your readme. I have asked few months on stackoverflow about how to print images and i referred in my answer your plugin.

**Comment by giorgiofellipe** [comment]
Glad to see it is useful. :laughing: 
Thank you!

**Comment by EmersonAlves** [comment]
Como é que faço pra imprimir uma imagem ? 
quanto tento imprimir ele sempre me retorna vários caracteres estranho

**Comment by giorgiofellipe** [comment]
@EmersonAlves **PLEASE ASK QUESTIONS ON [STACKOVERFLOW](https://stackoverflow.com) USING THE TAG cordova-plugin-datecs-printer**
