### ISSUE TITLE
Can't print accents and "Ç"

### ISSUE THREAD

**Issue by leonardofmed** [giorgiofellipe/cordova-plugin-datecs-printer#90]
Infelizmente eu de novo :/
Estou tentando imprimir vogais com acentos e o "ç", mas a impressora retorna outros caracteres. Estou usando ISO-8859-1.

Tento: ãéúçÇ
Imprime: 
![20180301_092255](https://user-images.githubusercontent.com/33374703/36844546-e98c2e1e-1d31-11e8-906b-eba16b2a1341.jpg)

Vou aproveitar a issue também para tirar uma outra dúvida rápida sobre o espaçamento. 
Meu código:

```
var printStr = "";
    for (var i = 0; i < 2; i++) {
      printStr += " {left}LEFT ";
      printStr += " {center}Center ";
      printStr += " {right}RIGHT ";
      printStr += "{br}";
    }

    this.print.printText(printStr, 'ISO-8859-1').then(result => {
      console.log(JSON.stringify(result));
      this.print = result;
    }).catch(err => {

    });
```
O que imprime: 
![20180301_095553](https://user-images.githubusercontent.com/33374703/36845694-7cc3fe60-1d36-11e8-93c5-2300715f90f7.jpg)

Obrigado desde já!

**Comment by giorgiofellipe** [comment]
1. Sua impressora suporta esses caracteres? Já tentou mexer na configuração da impressora?

2. Acredito que as impressoras ESC/POS não sejam capazes de reproduzir mais de um alinhamento por linha, para atingir esse objetivo você pode tentar a seguinte alternativa: conhecer a quantidade de colunas e preencher com espaços.

**Comment by leonardofmed** [comment]
1. Dei uma pesquisada e pelo que vi a impressora não suporta mesmo. 
2. Vou seguir essa alternativa.
Muito obrigado mais uma vez!
