### ISSUE TITLE
Como q eu coloco esse codigo no meu ionic????

### ISSUE THREAD

**Issue by pedroCirilo** [giorgiofellipe/cordova-plugin-datecs-printer#91]
@giorgiofellipe

**Comment by pedroCirilo** [comment]
@giorgiofellipe

**Comment by giorgiofellipe** [comment]
Cara infelizmente não posso te ensinar a trabalhar com Ionic, procure materiais na internet que falem sobre a utilização de plugins cordova com Ionic e observe os exemplos que te indiquei em outra issue.
