### ISSUE TITLE
QRcode not printed

### ISSUE THREAD

**Issue by Gunasekaran15** [giorgiofellipe/cordova-plugin-datecs-printer#94]
I tried to print QRcode with my EPSON TM-P20  printer,It prints text,image but it does't print QRcode,It shows the following error 
 **window.DatecsPrinter.printQRCode is not a function**

**Comment by giorgiofellipe** [comment]
Could you please share your code?

**Comment by Gunasekaran15** [comment]
This is my code


function call1() {
	
	

window.DatecsPrinter.listBluetoothDevices(
  function (devices) {
    window.DatecsPrinter.connect(devices[0].address, 
      function() { 
     printSomeTestText();
      // printMyBarcode();
     
     // printt();
     
     // printMyImage();
      },
      function() {
        alert(JSON.stringify(error));
      }
    );
  },
  function (error) {
    alert(JSON.stringify(error));
  }
);
//var a="HELLO GUYS "+{br}+"HOW ARE YOU,I'M  HAPPY";
function printSomeTestText() {
  window.DatecsPrinter.printText("{b}HELLO GUYS HOW ARE {/b}{br} YOU  I AM HAPPY.",'ISO-8859-1',success,error);
    function success() {
  //printMyImage();
      alert('success!');
      printQRCode();  
    }
    function error(){
alert(JSON.stringify(error));
    }
  
}
 //var data_en = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><h1>My First JavaScript</h1><button type="button">Click me to display Date and Time.</button><p id="demo"></p></body></html> ';	
	
  // window.DatecsPrinter.printPage(
  //   function() {
  //    // printMyImage();
  //     alert('success!');  
  //   }
  // );

// function printt() {
//   alert("a is:"+b);
//   window.DatecsPrinter.write(a,
//     function() {
//     alert('success!');  
//     }
//   );
//  //var data_en = '<!DOCTYPE html><html><head><meta charset="UTF-8"></head><body><h1>My First JavaScript</h1><button type="button">Click me to display Date and Time.</button><p id="demo"></p></body></html> ';	
	
//   // window.DatecsPrinter.printPage(
//   //   function() {
//   //    // printMyImage();
//   //     alert('success!');  
//   //   }
//   // );
// }


function printMyImage() {
  var image = new Image();
  image.src = 'img/logo.png';
  image.onload = function() {
      var canvas = document.createElement('canvas');
      canvas.height = 150;
      canvas.width = 150;
      var context = canvas.getContext('2d');
      context.drawImage(image,0, 0);
      var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove mimetype
      window.DatecsPrinter.printImage(
          imageData, //base64
          canvas.width, 
          canvas.height, 
           1,
          function() { alert('success!');
          //  printMyBarcode();
          //    printSomeTestText();
          },
          function(error) {
              alert(JSON.stringify(error));
          }
      )
  };
}



    function printQRCode(){


        
   alert("inside");
    var img = $("#qrcode").find('img'), // select images inside .container
        len = img.length; // check if they exist
        alert(len);
    if( len > 0 ){
        // images found, get id
        alert("inside if");
        var attrID = img.first().attr('src'); // get id of first image
        alert(attrID);
        console.log("attrID is "+attrID);
        var image = new Image();
        image.src = attrID;
        var canvas = document.getElement('canvas');
        canvas.height = 164;
        canvas.width = 164;
        // var context = canvas.getContext('2d');
        // console.log("context is "+context);
        //context.drawImage(image, 0, 0);
        //onsole.log("context is  "+context);
        var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove 
        
        console.log("image data is "+imageData);
        window.DatecsPrinter.printImage(
            imageData, //base64
            canvas.height, 
            canvas.width, 
            //align
            1,

            function() {
            },

            function(error) {
                alert(JSON.stringify(error));
            }
        );

        
        // var im=attrID;
        //console.log(im);
        // var a=im.replace('data:image/png;base64,','');
        //console.log(a);
        
      //var a=im.replace(/^data:image\/(png|jpg|jpeg);base64,/, "");
    
      //var context = canvas.getContext('2d');
      //context.drawImage(image,0, 0);
      //var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove mimetype
    //   console.log(a);
   

    } else {
        // images not found
        alert("QRcode print error");
    }




        }
   
    }
    $(document).ready(function(){


        var qrcode = new QRCode(document.getElementById("qrcode"), {
          text:"http://www.sample.com",
            
        });
        
    });

**Comment by Gunasekaran15** [comment]
function call1() {
	
	

window.DatecsPrinter.listBluetoothDevices(
  function (devices) {
    window.DatecsPrinter.connect(devices[0].address, 
      function() { 
     printSomeTestText();
      // printMyBarcode();
     
     // printt();
     
     // printMyImage();
      },
      function() {
        alert(JSON.stringify(error));
      }
    );
  },
  function (error) {
    alert(JSON.stringify(error));
  }
);
//var a="HELLO GUYS "+{br}+"HOW ARE YOU,I'M  HAPPY";
function printSomeTestText() {
  window.DatecsPrinter.printText("{b}HELLO GUYS HOW ARE {/b}{br} YOU  I AM HAPPY.",'ISO-8859-1',success,error);
    function success() {
  //printMyImage();
      alert('success!');
      printQRCode();  
    }
    function error(){
alert(JSON.stringify(error));
    }
  
}

function printMyImage() {
  var image = new Image();
  image.src = 'img/logo.png';
  image.onload = function() {
      var canvas = document.createElement('canvas');
      canvas.height = 150;
      canvas.width = 150;
      var context = canvas.getContext('2d');
      context.drawImage(image,0, 0);
      var imageData = canvas.toDataURL('image/jpeg').replace(/^data:image\/(png|jpg|jpeg);base64,/, ""); //remove mimetype
      window.DatecsPrinter.printImage(
          imageData, //base64
          canvas.width, 
          canvas.height, 
           1,
          function() { alert('success!');
          //  printMyBarcode();
          //    printSomeTestText();
          },
          function(error) {
              alert(JSON.stringify(error));
          }
      )
  };
}


function printQRCode() {
    window.DatecsPrinter.printQRCode(
      4, 
      4, 
      'http://giorgiofellipe.com.br',
      function() {
        alert('success!');
      },
      function() {
        alert(JSON.stringify(error));
      }
    );
  }
}

**Comment by giorgiofellipe** [comment]
Do you call this after cordova.isReady?

**Comment by Gunasekaran15** [comment]
yes

**Comment by giorgiofellipe** [comment]
Could you please create a repository with the problem isolated?
