### ISSUE TITLE
How to cut paper? (if available on printer)

### ISSUE THREAD

**Issue by arzanardi** [giorgiofellipe/cordova-plugin-datecs-printer#97]

**Comment by giorgiofellipe** [comment]
I'm not sure if all printer brands/models will respond to the same command to cut. Some of them do this when you send this hexadecimal code `1B69`. Please try it out or check your printer's manual.

```javascript
        window.DatecsPrinter.writeHex('1B69',
          function (success) {

          },
          function (error) {

          }
        );
```
